token:
  expiration_time: 864000000 
  secret: '{cipher}AQCGxoPQnMaVdVJTnHsUeSXLUDMo8n3kIWSuCOrLovZNlUiFJeQE1n2g04VRsQaRd6D+0I9s5acoFkQ3p+/ympgRKMZmQaBAcJjJjbdieOHLIL8sJ/ydJYQ6Vmy/E6wCNn82L846J4o/iG92fNmtxm6KCNBXmSwHSQpTonG0+XLbo7YKMfAU/ObxV+sKnrs7PENA9kDqhRyQ4QoUdWc461V/PRY4hMepUBz0RfYNmgxvlXE+x395h4v1OXUUztF5v4ORma9xsN/O6axgtkvoBbgNfPkZXK2ZuxJxeUc09qwYcAEmhu0JEplp8NVdlmEbFoJw4z6vSlWdQM5D0oMSzmMAZuEYBgoZTLcf5WD42RnTAU6e+chuGqMz2ML2UXtrqQmq5A7cI+ZV9SJ6cuarw3L+Zvv4i40LDadkxNjapKG4N9yWu4gi8SY3jeAbrayRRZ6rDQeUjlV1w5yXGNk+aJhB'  
gateway:
  ip: 172.18.0.1
