token:
  expiration_time: 864000000 
  secret: '{cipher}AQBcITHQIgIRy+yMtlhnpkhnkOSmO4Wh5rNYhUIQv6EQn3klxGBQGjcq0GL2axauNqDj1zmxMZRflpbmCZ5QdXcZni+Kuj5sE2ts2Fr+GzNeMOEU6Myc2GbK3eMONBkMwGS8ABFmZ0xGgAo5BbVfLRZP3icqdT4vHDaVfyQVrZFxe285pgAf6KmhBT2UMGQlV89/vEd06O682V+pXEOo7CEeOLOkj5prFYbRYipBs+vvX0OgUQmmWIGgnw3idA7/QeSM1i1VhdIzGp6qXIMgYxlZ9ZkJPOmcbK4cGGMpampmbVdXJpvqyNc415SyOJRDl3spgJOEQ0V1VlfWa9o/aDe6fpmRMNtNayjKjkPVKim91fp++OewN0L7qo+BGcjYZDixG5UmDS1tg5Zi52Xgy0jAj3IFiubj3my3s+OIuT7OmD+D9m4r5ybZgXw0/J79ggIrG3WWGr3CJwpEl3bTGuNA'
gateway:
  ip: 172.18.0.1
